version: '3.7'

services:
  task-planner:
    image: faisalwilmar/task-planner:latest
    restart: always
    environment:
      MONGO_USER: your_mongo_user
      MONGO_PASS: your_mongo_password
      MONGO_DB: your_mongo_database_name
    ports:
      - "12345:12345"


# reference https://docs.docker.com/samples/wordpress/